### ISSUE TITLE
[Design] Crop logo.png to 1:1 aspect ratio for circlar logo.

### ISSUE THREAD

**Issue by hXtreme** [hXtreme/hxtreme.github.io#7]
This makes it super straightforward to make a circular image by simply using:
```css
.logo {
    border-radius: 50%;
}
```

Add a test to check that the logo always has: `height = width`
